### ISSUE TITLE
Add UserName as a variable 

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/HWDSB-Elementary-Interface#1]
The widget code uses D2L replace strings in order to work. Up until this point we have only needed the OrgUnitID replace string. The Learn360 integration uses the UserName replace string. 

So I'm trying to sort out how to add UserName to this script: 

```
<script>// <![CDATA[
(function() {
                var contentFile = '/shared/fullwidthtabs/index.html';
                var iframe = document.createElement('iframe');
                iframe.addEventListener('load', function() {
                  var orgUnitId = {orgUnitId}; // this uses LE replace-strings
                  iframe.contentWindow.start(orgUnitId);
                });
                iframe.style.width = '100%';
                iframe.style.height = '700px';
                iframe.src = contentFile;
                document.currentScript.parentNode.insertBefore(iframe, document.currentScript);
              })();
// ]]></script>
```

I'm not sure if I can just add this in an array, or if I need a separate function:

`var UserName = {UserName}; // this uses LE replace-strings`

**Comment by bfowler** [comment]
Hi Jared,

You should be able to add that code to the load function and it will be injected into the created iframe. Since this is a string you would also need to put it in single quotes.

It also looks like the load script is running a function named `start()` in the iframe to pass the variable. I believe that you will have to edit this as well as the variable is likely locally scoped to the load function.

The complete code would look as follows:

```
<script>// <![CDATA[
(function() {
                var contentFile = '/shared/fullwidthtabs/index.html';
                var iframe = document.createElement('iframe');
                iframe.addEventListener('load', function() {
                  var orgUnitId = {orgUnitId}; // this uses LE replace-strings
                  var UserName = '{UserName}'; // this uses LE replace-strings
                  iframe.contentWindow.start(orgUnitId, UserName);
                });
                iframe.style.width = '100%';
                iframe.style.height = '700px';
                iframe.src = contentFile;
                document.currentScript.parentNode.insertBefore(iframe, document.currentScript);
              })();
// ]]></script>
```

This should work as long as `{UserName}` is replaced with the correct string by the LE.

**Comment by mrjarbenne** [comment]
It doesn't seem to like that. Is there a way to add an array of variables? Something like this? 

```
var tokens = [ orgUnitId = {orgUnitID}, UserName = {UserName} ]
iframe.contentWindow.start(tokens);
```

**Comment by bfowler** [comment]
What's the error you are getting? Do you have it running somewhere I can see it?

If it just simply isn't working, make sure you have re-written the start function to accept an additional parameter.

**Comment by mrjarbenne** [comment]
Fixed in https://github.com/hwdsbcommons/HWDSB-Elementary-Interface/commit/bca2a6848b8e749d23971a83d987dc2dc82a67ca
